In [1]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df.head()

0     1   2   3   4   5   6   7   8   9  ...  1016  1017  1018  1019  1020  \
0  0  1017  38  48  51  44  48  56  56  41  ...  84.0  83.0  81.0   NaN   NaN   
1  1   889  83  74  65  65  66  55  43  25  ...   NaN   NaN   NaN   NaN   NaN   
2  4  1017  19  10  -2  -9  -5   3   8   7  ...  29.0  21.0  16.0   NaN   NaN   
3  1  1017  17  29  36  26  21  17  17  13  ... -53.0 -37.0 -33.0   NaN   NaN   
4  8   952  77  74  69  70  76  75  76  75  ...   NaN   NaN   NaN   NaN   NaN   

   1021  1022  1023  1024  1025  
0   NaN   NaN   NaN   NaN   NaN  
1   NaN   NaN   NaN   NaN   NaN  
2   NaN   NaN   NaN   NaN   NaN  
3   NaN   NaN   NaN   NaN   NaN  
4   NaN   NaN   NaN   NaN   NaN  

[5 rows x 1026 columns]

In [4]:
df_temp = df.copy()

In [5]:
df_temp = df_temp.dropna(axis=1, thresh=60000)

In [6]:
df_temp

0     1    2    3    4    5    6    7    8    9  ...    943   944  \
0      0  1017   38   48   51   44   48   56   56   41  ...   58.0  82.0   
1      1   889   83   74   65   65   66   55   43   25  ...    NaN   NaN   
2      4  1017   19   10   -2   -9   -5    3    8    7  ...   58.0  55.0   
3      1  1017   17   29   36   26   21   17   17   13  ...    1.0  -1.0   
4      8   952   77   74   69   70   76   75   76   75  ...   81.0  72.0   
...   ..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   ...   
67630 -1  1024  138  135  123   96   59   38   11   16  ...  -14.0   5.0   
67631 -1  1024    4    5   -7  -12  -11  -17    2   52  ...  114.0  92.0   
67632 -1  1024   96  163  208  179  129  114  140  155  ...  -77.0   2.0   
67633 -1  1024  -30    4   53   85   84   72   80   85  ...   37.0  34.0   
67634 -1  1024   41   27   41   76   88   80   83   76  ...    2.0 -28.0   

        945    946    947    948    949    950    951    952  
0      96.0   92.0   92.0  103.0  118.0  136.0  146.0  145.0  
1       NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
2      66.0   71.0   74.0   74.0   73.0   64.0   35.0   25.0  
3       6.0   22.0   37.0   32.0    6.0   -1.0   16.0   25.0  
4      69.0   61.0   57.0   56.0   56.0   65.0   70.0   75.0  
...     ...    ...    ...    ...    ...    ...    ...    ...  
67630  25.0   22.0   -3.0  -34.0  -39.0  -35.0  -55.0  -74.0  
67631  88.0   89.0   84.0   64.0   65.0   59.0    8.0  -11.0  
67632  64.0   70.0   52.0   33.0   13.0   11.0    8.0    2.0  
67633  37.0   35.0   35.0   36.0   40.0   49.0   55.0   48.0  
67634 -92.0 -126.0 -116.0  -75.0  -26.0    1.0    1.0   10.0  

[67635 rows x 953 columns]

In [7]:
df_temp = df_temp.dropna(axis=0)

In [8]:
df_final = df_temp.drop(['1'], axis = 1)

In [9]:
df_final

0    2    3    4    5    6    7    8    9   10  ...    943   944   945  \
0      0   38   48   51   44   48   56   56   41   20  ...   58.0  82.0  96.0   
2      4   19   10   -2   -9   -5    3    8    7    8  ...   58.0  55.0  66.0   
3      1   17   29   36   26   21   17   17   13   17  ...    1.0  -1.0   6.0   
4      8   77   74   69   70   76   75   76   75   67  ...   81.0  72.0  69.0   
5      4   60   59   59   55   36   18   12   20   23  ...   72.0  71.0  53.0   
...   ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   ...   ...   
67630 -1  138  135  123   96   59   38   11   16   44  ...  -14.0   5.0  25.0   
67631 -1    4    5   -7  -12  -11  -17    2   52   73  ...  114.0  92.0  88.0   
67632 -1   96  163  208  179  129  114  140  155  108  ...  -77.0   2.0  64.0   
67633 -1  -30    4   53   85   84   72   80   85   65  ...   37.0  34.0  37.0   
67634 -1   41   27   41   76   88   80   83   76   60  ...    2.0 -28.0 -92.0   

         946    947    948    949    950    951    952  
0       92.0   92.0  103.0  118.0  136.0  146.0  145.0  
2       71.0   74.0   74.0   73.0   64.0   35.0   25.0  
3       22.0   37.0   32.0    6.0   -1.0   16.0   25.0  
4       61.0   57.0   56.0   56.0   65.0   70.0   75.0  
5       27.0   21.0   25.0   17.0   -7.0  -25.0  -25.0  
...      ...    ...    ...    ...    ...    ...    ...  
67630   22.0   -3.0  -34.0  -39.0  -35.0  -55.0  -74.0  
67631   89.0   84.0   64.0   65.0   59.0    8.0  -11.0  
67632   70.0   52.0   33.0   13.0   11.0    8.0    2.0  
67633   35.0   35.0   36.0   40.0   49.0   55.0   48.0  
67634 -126.0 -116.0  -75.0  -26.0    1.0    1.0   10.0  

[60641 rows x 952 columns]

In [10]:
total_Y = pd.get_dummies(df_final['0'])

In [11]:
total_Y

-1   0   1   2   3   4   5   6   7   8   9
0       0   1   0   0   0   0   0   0   0   0   0
2       0   0   0   0   0   1   0   0   0   0   0
3       0   0   1   0   0   0   0   0   0   0   0
4       0   0   0   0   0   0   0   0   0   1   0
5       0   0   0   0   0   1   0   0   0   0   0
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
67630   1   0   0   0   0   0   0   0   0   0   0
67631   1   0   0   0   0   0   0   0   0   0   0
67632   1   0   0   0   0   0   0   0   0   0   0
67633   1   0   0   0   0   0   0   0   0   0   0
67634   1   0   0   0   0   0   0   0   0   0   0

[60641 rows x 11 columns]

In [12]:
df_final = df_final.drop(['0'], axis=1) 

In [13]:
def normalize(df):
    arr = []
    for i,r in df.iterrows():
        #r = (r - r.min()) / (r.max() - r.min())
        #r = r/r.max()
        r = (r - r.mean()) / r.std()
        arr.append(r)
    df = pd.DataFrame(arr)
    print("Done")
    return df

df_final = normalize(df_final)

Done


In [14]:
df_final

2         3         4         5         6         7         8  \
0      0.009216  0.197698  0.254243  0.122305  0.197698  0.348484  0.348484   
2     -0.338030 -0.551126 -0.835254 -1.000995 -0.906286 -0.716867 -0.598481   
3     -0.362964 -0.069984  0.100920 -0.143229 -0.265304 -0.362964 -0.362964   
4      1.030537  0.960459  0.843662  0.867022  1.007178  0.983818  1.007178   
5      0.538847  0.515763  0.515763  0.423427 -0.015171 -0.430685 -0.569189   
...         ...       ...       ...       ...       ...       ...       ...   
67630  0.515012  0.498870  0.434301  0.289023  0.089938 -0.023056 -0.168334   
67631 -0.449117 -0.436105 -0.592251 -0.657312 -0.644300 -0.722373 -0.475142   
67632  0.835449  1.732568  2.335110  1.946805  1.277314  1.076466  1.424602   
67633 -0.980800 -0.431349  0.360506  0.877636  0.861475  0.667552  0.796834   
67634  0.156090 -0.076109  0.156090  0.736586  0.935613  0.802929  0.852685   

              9        10        11  ...       943       944       945  \
0      0.065761 -0.330052 -0.763562  ...  0.386181  0.838539  1.102414   
2     -0.622158 -0.598481 -0.740544  ...  0.585385  0.514353  0.774803   
3     -0.460624 -0.362964 -0.265304  ... -0.753603 -0.802433 -0.631529   
4      0.983818  0.796944  0.773584  ...  1.123974  0.913740  0.843662   
5     -0.384516 -0.315264 -0.707694  ...  0.815857  0.792772  0.377259   
...         ...       ...       ...  ...       ...       ...       ...   
67630 -0.141431  0.009228  0.132984  ... -0.302851 -0.200618 -0.093005   
67631  0.175466  0.448721  0.214502  ...  0.982219  0.695951  0.643903   
67632  1.625449  0.996127  0.299856  ... -1.480991 -0.423195  0.406975   
67633  0.877636  0.554429 -0.124304  ...  0.101941  0.053460  0.101941   
67634  0.736586  0.471216  0.670244  ... -0.490749 -0.988318 -2.049797   

            946       947       948       949       950       951       952  
0      1.027021  1.027021  1.234352  1.517076  1.856344  2.044826  2.025978  
2      0.893190  0.964222  0.964222  0.940544  0.727448  0.040807 -0.195966  
3     -0.240889  0.125335  0.003260 -0.631529 -0.802433 -0.387379 -0.167644  
4      0.656788  0.563350  0.539991  0.539991  0.750225  0.867022  0.983818  
5     -0.222928 -0.361432 -0.269096 -0.453769 -1.007787 -1.423301 -1.423301  
...         ...       ...       ...       ...       ...       ...       ...  
67630 -0.109147 -0.243664 -0.410465 -0.437368 -0.415845 -0.523459 -0.625692  
67631  0.656915  0.591854  0.331611  0.344623  0.266551 -0.397069 -0.644300  
67632  0.487314  0.246297 -0.008110 -0.275907 -0.302686 -0.342856 -0.423195  
67633  0.069620  0.069620  0.085780  0.150422  0.295864  0.392826  0.279704  
67634 -2.613708 -2.447852 -1.767842 -0.955147 -0.507335 -0.507335 -0.358064  

[60641 rows x 951 columns]

In [15]:
np_arr = np.array(df_final)

In [16]:
np_arr.shape

(60641, 951)

In [17]:
np_arr[0]

array([ 0.00921602,  0.19769846,  0.25424319,  0.12230548,  0.19769846,
        0.34848441,  0.34848441,  0.06576075, -0.33005238, -0.76356199,
       -0.87665146, -0.7258655 , -0.59392779, -0.61277604, -0.59392779,
       -0.38659711, -0.2546594 ,  0.00921602,  0.34848441,  0.36733266,
        0.27309144,  0.27309144,  0.19769846, -0.00963223,  0.02806426,
        0.25424319,  0.25424319,  0.04691251, -0.00963223, -0.06617696,
       -0.19811467, -0.23581116, -0.27350764, -0.31120413, -0.23581116,
       -0.00963223,  0.10345724,  0.14115373,  0.29193968,  0.36733266,
        0.42387739,  0.63120808,  0.66890456,  0.5558151 ,  0.3861809 ,
        0.25424319,  0.04691251,  0.04691251,  0.29193968,  0.65005632,
        0.95162823,  0.97047647,  0.95162823,  1.0270212 ,  0.95162823,
        0.81969052,  1.0270212 ,  1.49822731,  1.63016502,  1.5359238 ,
        1.61131677,  1.93173692,  2.0071299 ,  1.93173692,  2.06367463,
        2.12021936,  2.19561234,  2.15791585,  1.93173692,  1.76

In [18]:
# avg_val = []
# for val in np_arr:
#     #avg = sum(val[1:])/len(val[1:])
#     med = sorted(val[1:])
#     avg_val.append(med[len(med)//2])

In [19]:
total_X = np_arr
total_Y = np.array(total_Y)

In [20]:
total_X, total_Y

(array([[ 0.00921602,  0.19769846,  0.25424319, ...,  1.85634395,
          2.04482639,  2.02597814],
        [-0.33803025, -0.551126  , -0.83525366, ...,  0.72744847,
          0.04080663, -0.19596642],
        [-0.36296397, -0.06998442,  0.10092031, ..., -0.80243329,
         -0.38737893, -0.16764427],
        ...,
        [ 0.83544932,  1.73256789,  2.33511021, ..., -0.30268617,
         -0.34285566, -0.42319464],
        [-0.98079985, -0.43134938,  0.36050571, ...,  0.29586448,
          0.39282633,  0.27970417],
        [ 0.15608964, -0.07610896,  0.15608964, ..., -0.50733492,
         -0.50733492, -0.3580644 ]]),
 array([[0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        ...,
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0]], dtype=uint8))

In [26]:
labels = (np.array(df_temp['0'])).reshape(-1,1)
total_XY = np.append(labels, total_X, axis=1)

In [28]:
total_XY.shape

(60641, 952)

In [29]:
df_save = pd.DataFrame(total_XY)
df_save.to_csv("preprocess_train.csv", index=False)

In [30]:
X_train, X_test, Y_train, Y_test = train_test_split(total_X, total_Y, test_size=0.2)

In [31]:
X_train.shape

(48512, 951)

In [32]:
def create_model():
    
    model = tf.keras.models.Sequential([])
    
    model.add(tf.keras.layers.Dense(200, activation="relu"))
    
    model.add(tf.keras.layers.Dense(100, activation="relu"))
    
    model.add(tf.keras.layers.Dense(50, activation="relu"))
    model.add(tf.keras.layers.BatchNormalization())
    
    model.add(tf.keras.layers.Dense(11, activation="softmax"))
    
    return model

In [33]:
model = create_model()

In [34]:
model.compile(optimizer = tf.keras.optimizers.Adam(lr=0.01), loss="categorical_crossentropy", metrics=["accuracy"])

In [35]:
history = model.fit(X_train, Y_train, epochs = 10, validation_split=0.1, shuffle=True, verbose=1)

Epoch 1/10

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

1365/1365 [==============================] - 18s 13ms/step - loss: 2.3276 - accuracy: 0.2079 - val_loss: 2.2865 - val_accuracy: 0.2232
Epoch 2/10
1365/1365 [==============================] - 17s 12ms/step - loss: 2.2793 - accuracy: 0.2222 - val_loss: 2.2742 - val_accuracy: 0.2277
Epoch 3/10
1365/1365 [==============================] - 18s 13ms/step - loss: 2.2682 - accuracy: 0.2242 - val_loss: 2.2735 - val_accuracy: 0.2220
Epoch 4/10
1365/1365 [==============================] - 13s 9ms/step -

In [50]:
history = model.fit(X_train, Y_train, epochs = 5, validation_split=0.1, shuffle=True, verbose=1)

ResourceExhaustedError: OOM when allocating tensor with shape[43660,951] and type double on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:GatherV2]